name: mdb-dashboard

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: mdb-dashboard-backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=http://localhost
      - MDB_FILE_PATH=/app/data/your-database.mdb
      - DB_PATH=/app/data/temperature_data.sqlite
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/temperature-data"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mdb-dashboard-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  data:
    driver: local 